cd('C:\Users\Miller\Dropbox\josh\work\projects\Adam\HotHand\Data\statTheory')
addpath('C:\Users\Miller\Dropbox\josh\work\projects\Adam\HotHand\Data\statTheory')
rehash path

%Graph for Conditional Proportion
%Calls Ecprop(n,p,k).m
%   which depends on the file load PropData.mat
%       which is generated by WriteProp.m
%           *Note* we use WriteProp.m twice to create a finer grid, so we
%           need to merge. (%Afterwords combine with ProcessDataProp.m)
%

clear
nvalues=[2:1:30 40:10:100];
pvalues=.25:.25:.75;
kvalues=1:5;
nindex = @(n) find(nvalues==n);
pindex = @(p) find(pvalues==p);
prop=zeros(length(nvalues),length(pvalues),length(kvalues));

for n=nvalues
    for p=pvalues
        for k=kvalues
            prop(nindex(n),pindex(p),k)=Ecprop(n,p,k);
        end
    end
end


    A=squeeze(prop(:,1,:)); % The p=.25 values
    B=squeeze(prop(:,2,:));  % The p=.5 values
    C=squeeze(prop(:,3,:));  % The p=.75 values
    
    
mainfigure(nvalues, [A B C], nvalues, A, B, C)